services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: confeitaria-app
    container_name: confeitaria-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    working_dir: /var/www
    command: ./entrypoint.sh

  node:
    image: node:18
    container_name: confeitaria-node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: confeitaria-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
